# Generated by Django 2.1.3 on 2018-12-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='student',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
